
export const ACTIVITY_ACTIONS = {
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_DELETED: "PROJECT_DELETED",

  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_DELETED: "TASK_DELETED",

  TASK_STATUS_CHANGED:
    "TASK_STATUS_CHANGED",

  COMMENT_CREATED:
    "COMMENT_CREATED",

  COMMENT_UPDATED:
    "COMMENT_UPDATED",

  COMMENT_DELETED:
    "COMMENT_DELETED"
};